[theme]
primaryColor = "rgba(0, 0, 0, 1)"  # Black
backgroundColor = "rgba(250, 237, 205, 0.7)"  # Faded Beige
secondaryBackgroundColor = "rgba(240, 242, 246, 0.7)"  # Faded Light Gray
textColor = "#262730"  # Regular Text Color
font = "sans-serif"  # Sans Serif Font
